---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: data-platform
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: object-storage
    app.kubernetes.io/part-of: open-lakehouse-lab
    open-lakehouse-lab/stage: "03"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: object-storage
  ports:
    - name: s3-api
      port: 9000
      targetPort: s3-api
      protocol: TCP
    - name: console
      port: 9001
      targetPort: console
      protocol: TCP
