---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-worker
  namespace: data-platform
  labels:
    app.kubernetes.io/name: airflow
    app.kubernetes.io/component: worker-pod
    app.kubernetes.io/part-of: open-lakehouse-lab
    open-lakehouse-lab/stage: "05"
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-pod-launcher
  namespace: data-platform
  labels:
    app.kubernetes.io/name: airflow
    app.kubernetes.io/component: scheduler-rbac
    app.kubernetes.io/part-of: open-lakehouse-lab
    open-lakehouse-lab/stage: "05"
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["create", "delete", "get", "list", "patch", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-scheduler-pod-launcher
  namespace: data-platform
  labels:
    app.kubernetes.io/name: airflow
    app.kubernetes.io/component: scheduler-rbac
    app.kubernetes.io/part-of: open-lakehouse-lab
    open-lakehouse-lab/stage: "05"
subjects:
  - kind: ServiceAccount
    name: airflow-scheduler
    namespace: data-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-pod-launcher
