---
apiVersion: v1
kind: Secret
metadata:
  name: polaris-local-credentials
  namespace: data-platform
  labels:
    app.kubernetes.io/name: polaris
    app.kubernetes.io/component: catalog
    app.kubernetes.io/part-of: open-lakehouse-lab
    open-lakehouse-lab/stage: "04"
type: Opaque
stringData:
  POLARIS_ROOT_CLIENT_ID: change-me-root-client-id
  POLARIS_ROOT_CLIENT_SECRET: change-me-root-client-secret
  AWS_ACCESS_KEY_ID: change-me-minio-access-key
  AWS_SECRET_ACCESS_KEY: change-me-minio-secret-key
